Repository aaps4all/aap-site-revamping, pull requests merged in 2021-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: documentation

#3 new team UI added
  about.html
  css/meet_team.css
Labels: hacktoberfest-accepted

#4 gym page added
  contact.html
  gym.html
  img/logo.jpg
  img/ss.jpg
  index.html
Labels: hacktoberfest-accepted

#5 about page changed
  about.html
  img/business-3.png
Labels: hacktoberfest-accepted

#7 added logic for time selection based on the delivery acceptance
  serviceone.html
Labels: enhancement, hacktoberfest-accepted

#8 services addded and modified the home page
  about.html
  index.html
Labels: enhancement, hacktoberfest-accepted

#9 added delivey date and javascript handling function for alert etc
  contact_confirmation.html
  serviceone.html
Labels: hacktoberfest-accepted
